### ISSUE TITLE
Feature Request - Setup de toutes les catégories de prix dans le menu de création de produit

### ISSUE THREAD

**Issue by GoldmanEquinox** [yyewolf/bar#10]

**Comment by yyewolf** [comment]
Comment ça fonctionnerait ?

**Comment by GoldmanEquinox** [comment]
En gros quand on créé un produit, on ne peut que choisir un prix (genre que le prix de base). 
ça serait plus pratique de pouvoir setup tous les prix (de base, ceten, vip, etc.) au moment de la création du produit

**Comment by yyewolf** [comment]
Ah bah c'est fait alors
