### ISSUE TITLE
Feature Request - Surnom et Photo de Profil

### ISSUE THREAD

**Issue by GoldmanEquinox** [yyewolf/bar#17]
Éditable pour chaque compte via le panel admin

**Comment by yyewolf** [comment]
La photo de profil est synchro avec le compte google, elle peut aussi être modif avec gravatar mais bon pas assez mainstream :/

**Comment by GoldmanEquinox** [comment]
Pas possible d'avoir stocké en DB une image pour chaque personne ? Comme ça on a des PP personnalisables à volonté :)

**Comment by yyewolf** [comment]
Ils pourront pas changer d'image sur la borne de toute manière, donc faire un menu qui redirige vers la page de changement de PP de google c'est pas déconnant ?
