### ISSUE TITLE
Feature Request - Dates de péremption

### ISSUE THREAD

**Issue by GoldmanEquinox** [yyewolf/bar#26]
Date de péremption pour un produit (ATTENTION aux restock entretemps)
Alertes sur le panel admin X jours avant péremption d'un produit (X à définir sur ce-dit panel admin)
Promotion de 20% automatique X jours avant péremption (X à définir sur ce-dit panel admin)
Affichage sur le caroussel des promotions en cours

**Comment by yyewolf** [comment]
J'ai eu des retours me disant que c'est pas ouf ?
Ca impliquerait de forcer une entrée de toute les dates sans faire d'erreur...

**Comment by GoldmanEquinox** [comment]
Ça serait bien que ça ne soit pas obligatoire mais qu'on puisse le faire... Au cas où on aurait besoin je me dis...
Je demande demain à tout le bar pour savoir les avis et je te redis

**Comment by quilitane** [comment]
je verrai ca comme ca : le respo log vérifie deja les dates régulièrement. lorsqu'il détecte une date proche de la péremption, il rentre la date de la péremption et le nombre de produits à cette date. Les produits apparaissent alors dans un onglet promo 3 jour avant d'être périmés, en réduc jusqu'au jour signifié. lorsque la date est dépassée, les produits sont signifié comme périmé, ca poste une alerte (genre pop up en rouge?) pour les enlever et enlève le nombre de produits périmé du stock automatiquement. la premiere personne qui arrive sur le panel admin valide le pop up pour valider le retrait de la DB
