### ISSUE TITLE
Feature Request -  Panel Admin Trésorerie - Caisse virtuelle liquide

### ISSUE THREAD

**Issue by adrien-lrsse** [yyewolf/bar#49]
**Valeur de la caisse liquide**
A chaque rechargement liquide -> la caisse est incrémentée de la valeur du rechargement
A chaque remboursement liquide -> la caisse est décrémentée de la valeur du rechargement

On peut **mettre à jour la valeur** de la caisse (quand on compte la vraie caisse)
Pour mettre à jour la valeur de la caisse on rentre :
- le nbr de pièce de 1cts
- le nbr de pièce de 2cts
- le nbr de pièce de 5cts
- le nbr de pièce de 10cts
- le nbr de pièce de 20cts
- le nbr de pièce de 50cts
- le nbr de pièce de 1€
- le nbr de pièce de 2€
- le nbr de billet de 5€
- le nbr de billet de 10€
- le nbr de billet de 20€
- le nbr de billet de 50€

On peut transferer (virtuellement) l'argent de la caisse Bar vers (virtuellement) la caisse BDE
Cela permet pour la trésorerie de garder un historique des transferts de caisse
Cet historique doit être consultable sur ce même onglet (valeur du transfert, caisse entrante, caisse sortante, responsable du transfert, date de transfert)

**Comment by Ciflire** [comment]
Est-ce que on mettrait pas pour l'option liquide la possibilité de remplir la monnaie qui a été donnée?
Et surtout faudrait pouvoir traquer les modifications dans la caisse, et sécuriser tout ça pour pas qu'on puisse y toucher parce qu'un billet même dans une db est si vite supprimé

**Comment by adrien-lrsse** [comment]
> Est-ce que on mettrait pas pour l'option liquide la possibilité de remplir la monnaie qui a été donnée? Et surtout faudrait pouvoir traquer les modifications dans la caisse, et sécuriser tout ça pour pas qu'on puisse y toucher parce qu'un billet même dans une db est si vite supprimé

Pas sur de l'utilité, ça va alourdir le processus de rechargement et l'information n'est pas utile pour la trésorerie

**Comment by Ciflire** [comment]
On est bien d'accord qu'on ne stocke pas le contenue de la caisse mais simplement une unique valeur qui est le contenu de la caisse et que tu tien manuellement à jour quand tu la vides et qui est mis à jour quant on fait un rechargement en espèce

**Comment by adrien-lrsse** [comment]
oui le détail de la caisse réelle sert uniquement à ne pas se tromper sur la valeur de la caisse quand on met à jour la caisse virtuelle

**Comment by Ciflire** [comment]
ok donc ce serait un reapprovisionnement de la caisse dans le front mais dans le back on ne stockerait que le total

**Comment by yyewolf** [comment]
https://github.com/yyewolf/bar/commit/f3152f0fd120f2f74655fe995de6d90c6dabc407
