### ISSUE TITLE
Feature Request - Panel Admin Trésorerie - Historique d'achat d'un produit sur une période

### ISSUE THREAD

**Issue by adrien-lrsse** [yyewolf/bar#50]
Dans le panel Trésorerie, il faut pouvoir pour un produit / un menu selectionné, consulter entre deux dates l'historique de d'achat d'un produit / menu.
Il faut pouvoir voir consulter
- le prix d'achat de chaque client du dit produit/menu
- le nbr total de commande
- la valeur de toutes les commandes sur cette période

Note : il faut bien penser à enlever des résultats les commandes annulées.

**Comment by yyewolf** [comment]
https://github.com/yyewolf/bar/commit/65cca30964d47c285ab942fa6097509ff5c95090
