### ISSUE TITLE
[ URGENT ] fix de la reappro

### ISSUE THREAD

**Issue by Ciflire** [yyewolf/bar#51]
- [x] Réinitialisation du prix lors de la saisie de la TVA
- [x] Saisir par défaut dans les champs les prix d'origine
- [x] Prix en centimes et non en euro
- [x] Non réinitialisation de la liste des produits réapprovisionnés

**Comment by GoldmanEquinox** [comment]
J'insiste que je peux pas faire ma réappro d'hier soir tant que j'ai pas ça 👀

**Comment by yyewolf** [comment]
https://github.com/yyewolf/bar/commit/eaab08ea1fc6a08874b1e7953ff091934f9f4f93
