### ISSUE TITLE
Feature request - historique des rechargements

### ISSUE THREAD

**Issue by KiriBaton** [yyewolf/bar#53]
Il faudrait quelque part dans l'app une page qui résume les rechargements pour vérifier la cohérence avec les tickets.
Il faudrait pouvoir accéder aux tickets jour par jour. Les tickets devraient être classés par ordre chronologique dans les différentes catégories de rechargement (carte, espèce, autre)
Dans l'idéal, sur la page on voit :
- la date des rechargements affichés
- le nombre de rechargements dans chaque catégorie
- le total d'argent généré dans chaque catégorie

pour chaque rechargement, les infos les plus importantes à afficher sont :
- nom-prénom de la personne qui a autorisé le rechargement
- nom-prénom de la personne qui a été rechargée
- montant du rechargement
- heure du rechargement

**Comment by yyewolf** [comment]
https://github.com/yyewolf/bar/commit/c5eda25678866723f171484b62cbe5a7033b8e18
